# Generated by Django 4.1.7 on 2023-02-28 11:36

import uuid
from datetime import datetime

from django.db import migrations

NAMESPACE_ID = uuid.UUID('6ba7b816-9dad-11d1-80b4-00c04fd430c8')


def get_uuid(value, namespace=NAMESPACE_ID):
    return str(uuid.uuid5(namespace=namespace, name=value))


def get_now():
    return str(datetime.utcnow())


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            f"""
                INSERT INTO content.main_menu (id, name, detailed_name, created, modified) 
                VALUES ('{get_uuid('01')}', 'Top menu', 'First main menu', '{get_now()}', '{get_now()}');

                INSERT INTO content.menu_item (id, name, path, main_menu_id, parent_id, created, modified) 
                VALUES 
                    ('{get_uuid('11')}', 'Main', 'main', '{get_uuid('01')}', null, '{get_now()}', '{get_now()}'),
                    ('{get_uuid('12')}', 'About', 'about_us', '{get_uuid('01')}', null, '{get_now()}', '{get_now()}'),
                    ('{get_uuid('13')}', 'Top level', 'top_level', '{get_uuid('01')}', null, '{get_now()}', '{get_now()}'),
                    ('{get_uuid('14')}', 'Sub-item 14', 'sub-item_14', '{get_uuid('01')}', '{get_uuid('13')}', '{get_now()}', '{get_now()}'),
                    ('{get_uuid('15')}', 'Sub-item 15', 'sub-item_15', '{get_uuid('01')}', '{get_uuid('13')}', '{get_now()}', '{get_now()}'),
                    ('{get_uuid('16')}', 'Sub-item 16', 'sub-item_16', '{get_uuid('01')}', '{get_uuid('15')}', '{get_now()}', '{get_now()}'),
                    ('{get_uuid('17')}', 'Item 17', 'item_17', '{get_uuid('01')}', '{get_uuid('15')}', '{get_now()}', '{get_now()}'),
                    ('{get_uuid('18')}', 'Item 18', 'item_18', '{get_uuid('01')}', '{get_uuid('15')}', '{get_now()}', '{get_now()}'),
                    ('{get_uuid('19')}', 'Item 19', 'item_19', '{get_uuid('01')}', '{get_uuid('16')}', '{get_now()}', '{get_now()}'),    
                    ('{get_uuid('110')}', 'Links', 'links', '{get_uuid('01')}', null, '{get_now()}', '{get_now()}'),
                    ('{get_uuid('111')}', 'Python', 'https://dzen.ru/python', '{get_uuid('01')}', '{get_uuid('110')}', '{get_now()}', '{get_now()}');
            """)
    ]
